- name: Deploy LB
  hosts: load_balancer
  vars_files:
    - settings.yml
  tasks:
    - include_tasks: tasks/haproxy.yml

- name: Deploy Vault
  hosts: nodes
  vars_files:
    - settings.yml
  tasks:
    - include_tasks: tasks/vault.yml
