---
- name: Install HAProxy
  yum:
    name: haproxy
    state: present

- name: Create /etc/ssl/private
  file:
    path: /etc/ssl/private
    state: directory

- name: SCP SSL cert to LB at /etc/ssl/private
  copy:
    src: "{{ load_balancer_tls_cert_path }}"
    dest: /etc/ssl/private/vault.crt
  when: not tls_disabled

- name: SCP SSL key to LB at /etc/ssl/private
  copy:
    src: "{{ load_balancer_tls_key_path }}"
    dest: /etc/ssl/private/vault.key
  when: not tls_disabled

- name: Install HAProxy
  yum:
    name: haproxy
    state: present

- name: SCP firewalld HAProxy service HTTP config file
  copy:
    content: |
      <?xml version="1.0" encoding="utf-8"?>
      <service>
        <short>Vault</short>
        <description>Vault LB</description>
        <port protocol="tcp" port="80"/>
      </service>
    dest: /etc/firewalld/services/haproxy-http.xml
    owner: root
    group: root
    mode: 0640

- name: SCP firewalld HAProxy service HTTPS config file
  copy:
    content: |
      <?xml version="1.0" encoding="utf-8"?>
      <service>
        <short>Vault</short>
        <description>Vault LB</description>
        <port protocol="tcp" port="443"/>
      </service>
    dest: /etc/firewalld/services/haproxy-https.xml
    owner: root
    group: root
    mode: 0640
  when: not tls_disabled

- name: Reset security context on HAProxy service HTTP and HTTPS config files
  shell: |
    restorecon /etc/firewalld/services/haproxy-http.xml
    restorecon /etc/firewalld/services/haproxy-https.xml

- name: Create PEM cert and set permissions
  shell: |
    cat /etc/ssl/private/vault.crt /etc/ssl/private/vault.key > /etc/ssl/private/vault.pem
    chmod 600 /etc/ssl/private/{vault.pem,vault.crt,vault.key}
  when: not tls_disabled

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Allow dest port 8200 selinux
  seport:
    ports: 8200
    proto: tcp
    setype: http_port_t
    state: present

- name: Create logging file configuration for HAProxy
  copy:
    content: |
      local0.* /var/log/haproxy-traffic.log
      local0.notice /var/log/haproxy-admin.log
    dest: /etc/rsyslog.d/haproxy.conf

- name: Restart the rsyslog service
  service:
    name: rsyslog
    state: restarted

- name: Start and enable the HAProxy service
  service:
    name: haproxy
    state: started
    enabled: yes
